Quals/Web/Solo/solo_server/myapp/config/routes.rb
Rails.application.routes.draw do
  # Add a root route if you don't have one...
  # We can use users#new for now, or replace this with the controller and action you want to be the site root:
  root to: 'users#new'

  # sign up page with form:
  get '/register' => 'users#new', as: :new_user

  # create (post) action for when sign up form is submitted:
  post 'users' => 'users#create'

  # log in page with form:
  get '/login' => 'sessions#new'

  # create (post) action for when log in form is submitted:
  post '/login' => 'sessions#create'

  # delete action to log out:
  delete '/logout' => 'sessions#destroy'
  
  # OPTIONAL secret page (requires a user to be signed in):

  get 'pages/share' => 'pages#show'

  get 'pages/new' => 'pages#new'

  post 'pages' => 'pages#create'

end

Quals/Web/Solo/solo_server/myapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Quals/Web/Solo/solo_server/myapp/app/models/page.rb
class Page < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 1, maximum: 50 }
  validates :text, presence: true,
                    length: { minimum: 1, maximum: 100 }
end

Quals/Web/Solo/solo_server/myapp/app/models/user.rb
class User < ApplicationRecord
	# ----- add these lines here: -----
	
	has_secure_password

	# Verify that email field is not blank and that it doesn't already exist in the db (prevents duplicates):
	validates :email, presence: true, uniqueness: true
	
	# ----- end of added lines -----
end

Quals/Web/Solo/solo_server/myapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Make the current_user method available to views also, not just controllers:
  helper_method :current_user

  # Define the current_user method:
  def current_user
    # Look up the current user based on user_id in the session cookie:
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  # authroize method redirects user to login page if not logged in:
  def authorize
    redirect_to login_path, alert: 'You must be logged in to access this page.' if current_user.nil?
  end
  
end

Quals/Web/Solo/solo_server/myapp/app/controllers/pages_controller.rb
class PagesController < ApplicationController

	before_action :authorize, only: [:show, :new, :create]

	def show
		if Page.exists? params[:page_id]
			@page = Page.find(params[:page_id])
		else
			@page = nil
		end
	end

	def new
	 	@page = Page.new
	end
	 
	def create
	 	@page = Page.new(page_params)
	 
	 	if @page.save
	 		flash[:notice] = "Sharing Page Success !"
			redirect_to root_path
		else
			render 'new'
		end
	end
	 
	private
		def page_params
			params.require(:page).permit(:title, :text)
		end
end

Quals/Web/Solo/solo_server/myapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # No need for anything in here, we are just going to render our
    # new.html.erb AKA the login page
  end

  def create
    # Look up User in db by the email address submitted to the login form and
    # convert to lowercase to match email in db in case they had caps lock on:
    user = User.find_by(email: params[:login][:email].downcase)

    # Verify user exists in db and run has_secure_password's .authenticate()
    # method to see if the password submitted on the login form was correct:
    if user && user.authenticate(params[:login][:password])
      # Save the user.id in that user's session cookie:
      session[:user_id] = user.id.to_s
      redirect_to root_path, notice: 'Successfully logged in!'
    else
      # if email or password incorrect, re-render login page:
      flash.now.alert = "Incorrect email or password, try again."
      render :new
    end
  end

  def destroy
    # delete the saved user_id key/value from the cookie:
    session.delete(:user_id)
    redirect_to login_path, notice: "Logged out!"
  end

end

Quals/Web/Solo/solo_server/myapp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    # store all emails in lowercase to avoid duplicates and case-sensitive login errors:
    @user.email.downcase!

    if @user.save
      # If user saves in the db successfully:
      flash[:notice] = "Account created successfully!"
      redirect_to root_path
    else
      # If user fails model validation - probably a bad password or duplicate email:
      flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
      render :new
    end
  end

  private

  def user_params
    # strong parameters - whitelist of allowed fields #=> permit(:name, :email, ...)
    # that can be submitted by a form to the user model #=> require(:user)
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

Quals/Web/Solo/solo_server/myapp/app/helpers/application_helper.rb
module ApplicationHelper
end

Quals/Web/Solo/solo_server/myapp/app/helpers/pages_helper.rb
module PagesHelper
end

Quals/Web/Solo/solo_server/myapp/app/helpers/sessions_helper.rb
module SessionsHelper
end

Quals/Web/Solo/solo_server/myapp/app/helpers/users_helper.rb
module UsersHelper
end

Quals/Web/Solo/solo_server/myapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>

  </head>

  <body>

    <!-- show nav links -->
    <% if current_user %>
      <!-- current_user will return true if a user is logged in -->
      <%= "Logged in as #{current_user.email}" %> | <%= link_to 'Home', root_path %> | <%= link_to 'Log Out', logout_path, method: :delete %>
    <% else %>
      <!-- not logged in -->
      <%= link_to 'Home', root_path %> | <%= link_to 'Log In', login_path %> or <%= link_to 'Sign Up', new_user_path %>
    <% end %>
    <hr>
    <!-- end -->

    <!-- show flash message if any: -->
    <% if notice %>
      <%= notice %>
    <% end %>

    <% if alert %>
      <%= alert %>
    <% end %>
    <!-- end -->

    <%= yield %>
  </body>
</html>

Quals/Web/Solo/solo_server/myapp/app/views/pages/new.html.erb
<%= form_with scope: :page, url: pages_path, local: true do |form| %>
 
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@page.errors.count, "error") %> prohibited
        this page from being saved:
      </h2>
      <ul>
        <% @page.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', pages_path %>

Quals/Web/Solo/solo_server/myapp/app/views/pages/show.html.erb
<% if @page %>
	<% if current_user.id == 1 %>
		<p>
		  <strong>Title:</strong>
		  <%= @page.title %>
		</p>
		 
		<p>
		  <strong>Text:</strong>
		  <%= @page.text %>
		</p>
	<% else %>
		Bukan admin
	<% end %>
<% else %> 
   Not exist
<% end %>

Quals/Web/Solo/solo_server/myapp/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Sign up!" %>
  </div>
<% end %>